"""Generate a print-ready PDF report of the full network analysis.

No extra dependency needed - reuses the matplotlib that is already in
requirements.txt. It embeds the PNG charts and lays out the key stats and
alerts into a multi-page PDF.

Used by BOTH the CLI (scripts/analyzer.py) and the web app (app.py).
Writing it here once keeps the report format identical everywhere.

Output: reports/network_traffic_report.pdf
"""

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import pandas as pd
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib.pyplot as plt

BASE_DIR = Path(__file__).resolve().parent.parent
REPORTS_DIR = BASE_DIR / "reports"

# Dashboard-style dark palette
NAVY = "#0b2646"
DARK = "#16213e"
TEAL = "#00adb5"
LIGHT = "#e8eef7"
GRAY = "#8f9bb8"
WHITE = "#ffffff"

CHART_FILES = ["protocol_chart.png", "top_ports_chart.png"]

CSV_FILES = {
    "Protocol Distribution": "traffic_report.csv",
    "Top Source IPs": "top_source_ips.csv",
    "Top Destination IPs": "top_destination_ips.csv",
    "Top Destination Ports": "top_destination_ports.csv",
    "Threat Alerts": "suspicious_ips.csv",
}


def _load_df(filename):
    path = REPORTS_DIR / filename
    if not path.exists():
        return None
    try:
        return pd.read_csv(path)
    except Exception:
        return None


def _draw_table(fig, ax, df, title):
    fig.patch.set_facecolor(NAVY)
    ax.set_facecolor(DARK)
    ax.set_xticks([])
    ax.set_yticks([])
    for spine in ax.spines.values():
        spine.set_edgecolor("#2a3a5a")

    cols = list(df.columns)
    rows = df.head(20).astype(str).values.tolist()
    table = ax.table(
        cellText=rows,
        colLabels=cols,
        cellLoc="left",
        loc="upper left",
        colWidths=[0.35] * len(cols),
    )
    table.auto_set_font_size(False)
    table.set_fontsize(8)
    table.scale(1.0, 1.3)

    for (row, col), cell in table.get_celld().items():
        cell.set_edgecolor("#2a3a5a")
        if row == 0:
            cell.set_facecolor(TEAL)
            cell.set_text_props(color=WHITE, fontweight="bold")
        else:
            cell.set_facecolor(DARK if row % 2 else "#1c2b4a")
            cell.set_text_props(color=LIGHT)

    ax.set_title(title, color=WHITE, fontsize=13, fontweight="bold", pad=14)


def save_pdf_report() -> Path:
    """Assemble all charts + CSV summaries into a single PDF."""

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = REPORTS_DIR / "network_traffic_report.pdf"

    with PdfPages(str(out_path)) as pdf:
        # ---- Title page ----
        fig = plt.figure(figsize=(8.27, 11.69))
        fig.patch.set_facecolor(NAVY)
        fig.text(
            0.5, 0.78, "Network Traffic Analyzer",
            color=WHITE, fontsize=30, fontweight="bold",
            ha="center", va="center",
        )
        fig.text(
            0.5, 0.72, "Threat Detection Report",
            color=TEAL, fontsize=18, ha="center",
        )
        fig.text(
            0.5, 0.62,
            "Protocol statistics, top hosts & ports, capture timing,\n"
            "and statistical anomaly detection - auto-generated for analyst review.",
            color=LIGHT, fontsize=11, ha="center", va="center", linespacing=1.5,
        )
        fig.text(
            0.5, 0.05,
            "Generated by Network-Traffic-Analysis | For Cyber Security internship exhibition",
            color=GRAY, fontsize=9, ha="center",
        )
        pdf.savefig(fig)
        plt.close(fig)

        # ---- Chart pages ----
        for chart_file in CHART_FILES:
            chart_path = REPORTS_DIR / chart_file
            if not chart_path.exists():
                continue
            fig = plt.figure(figsize=(8.27, 11.69))
            fig.patch.set_facecolor(NAVY)
            img = plt.imread(chart_path)
            ax = fig.add_axes([0.08, 0.1, 0.84, 0.8])
            ax.imshow(img)
            ax.axis("off")
            ax.set_title(
                chart_file.replace("_", " ").replace(".png", "").title(),
                color=WHITE, fontsize=14, fontweight="bold", pad=12,
            )
            pdf.savefig(fig)
            plt.close(fig)

        # ---- Data table pages ----
        for title, filename in CSV_FILES.items():
            df = _load_df(filename)
            if df is None or df.empty:
                continue
            fig = plt.figure(figsize=(8.27, 11.69))
            ax = fig.add_axes([0.07, 0.08, 0.86, 0.84])
            _draw_table(fig, ax, df, title)
            pdf.savefig(fig)
            plt.close(fig)

    return out_path


if __name__ == "__main__":
    path = save_pdf_report()
    print(f"PDF report saved: {path}")
